version: '3.1'

services:
   db:
     image: mysql:5.7
     volumes:
       - db-data:/var/lib/mysql
       - ./db-backup:/backup
     ports:
       - "3306:3306"
     restart: "no"
     environment:
       MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
       MYSQL_DATABASE: ${DB_NAME}
       MYSQL_USER: ${DB_USER}
       MYSQL_PASSWORD: ${DB_PASSWORD}

   phpmyadmin:
     image: phpmyadmin/phpmyadmin
     ports:
       - "8080:80"
     restart: "no"
     environment:
       PMA_HOST: db
       MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
       MYSQL_USER: ${DB_USER}
       MYSQL_PASSWORD: ${DB_PASSWORD}

   wordpress:
     image: wordpress:latest
    #  build: ./docker-files/wordpress
     depends_on:
       - db
     volumes:
       - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
       - ./wp-content:/var/www/html/wp-content
       - ./wp-src:/var/www/html
       - wp-code:/var/www/html
       - wp-src:/usr/src/wordpress
     ports:
       - "8000:80"
     restart: "no"
     environment:
       WORDPRESS_VERSION: 4.9.7
       WP_ENV: ${WP_ENV}
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: ${DB_USER}
       WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}

   wordpress-tools:
     build: ./docker-files/wp-tools
     depends_on:
       - wordpress
     volumes:
       - wp-code:/var/www/html
       - ./wp-content:/var/www/html/wp-content
       - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
     environment:
       XDEBUG_VERSION: 2.6.0
       XDEBUG_CONFIG: remote_host=172.17.0.1 #docker network ip.

   composer:
     image: composer:latest
     depends_on:
       - wordpress
     volumes:
       - .:/app
       - $COMPOSER_HOME:/tmp
      
volumes:
   db-data:
   wp-src:
   wp-code:
